#ifndef __SYSCALL_META
#define __SYSCALL_META

struct syscall_meta syscall_meta_table[] = {
    { "read", &fprint_syscall_read },
    { "write", &fprint_syscall_write },
    { "open", &fprint_syscall_default },
    { "close", &fprint_syscall_default },
    { "stat", &fprint_syscall_default },
    { "fstat", &fprint_syscall_default },
    { "lstat", &fprint_syscall_default },
    { "poll", &fprint_syscall_default },
    { "lseek", &fprint_syscall_default },
    { "mmap", &fprint_syscall_default },
    { "mprotect", &fprint_syscall_default },
    { "munmap", &fprint_syscall_default },
    { "brk", &fprint_syscall_default },
    { "rt_sigaction", &fprint_syscall_default },
    { "rt_sigprocmask", &fprint_syscall_default },
    { "rt_sigreturn", &fprint_syscall_default },
    { "ioctl", &fprint_syscall_default },
    { "pread64", &fprint_syscall_default },
    { "pwrite64", &fprint_syscall_default },
    { "readv", &fprint_syscall_default },
    { "writev", &fprint_syscall_default },
    { "access", &fprint_syscall_default },
    { "pipe", &fprint_syscall_default },
    { "select", &fprint_syscall_default },
    { "sched_yield", &fprint_syscall_default },
    { "mremap", &fprint_syscall_default },
    { "msync", &fprint_syscall_default },
    { "mincore", &fprint_syscall_default },
    { "madvise", &fprint_syscall_default },
    { "shmget", &fprint_syscall_default },
    { "shmat", &fprint_syscall_default },
    { "shmctl", &fprint_syscall_default },
    { "dup", &fprint_syscall_default },
    { "dup2", &fprint_syscall_default },
    { "pause", &fprint_syscall_default },
    { "nanosleep", &fprint_syscall_default },
    { "getitimer", &fprint_syscall_default },
    { "alarm", &fprint_syscall_default },
    { "setitimer", &fprint_syscall_default },
    { "getpid", &fprint_syscall_default },
    { "sendfile", &fprint_syscall_default },
    { "socket", &fprint_syscall_default },
    { "connect", &fprint_syscall_default },
    { "accept", &fprint_syscall_default },
    { "sendto", &fprint_syscall_default },
    { "recvfrom", &fprint_syscall_default },
    { "sendmsg", &fprint_syscall_default },
    { "recvmsg", &fprint_syscall_default },
    { "shutdown", &fprint_syscall_default },
    { "bind", &fprint_syscall_default },
    { "listen", &fprint_syscall_default },
    { "getsockname", &fprint_syscall_default },
    { "getpeername", &fprint_syscall_default },
    { "socketpair", &fprint_syscall_default },
    { "setsockopt", &fprint_syscall_default },
    { "getsockopt", &fprint_syscall_default },
    { "clone", &fprint_syscall_default },
    { "fork", &fprint_syscall_default },
    { "vfork", &fprint_syscall_default },
    { "execve", &fprint_syscall_default },
    { "exit", &fprint_syscall_default },
    { "wait4", &fprint_syscall_default },
    { "kill", &fprint_syscall_default },
    { "uname", &fprint_syscall_default },
    { "semget", &fprint_syscall_default },
    { "semop", &fprint_syscall_default },
    { "semctl", &fprint_syscall_default },
    { "shmdt", &fprint_syscall_default },
    { "msgget", &fprint_syscall_default },
    { "msgsnd", &fprint_syscall_default },
    { "msgrcv", &fprint_syscall_default },
    { "msgctl", &fprint_syscall_default },
    { "fcntl", &fprint_syscall_default },
    { "flock", &fprint_syscall_default },
    { "fsync", &fprint_syscall_default },
    { "fdatasync", &fprint_syscall_default },
    { "truncate", &fprint_syscall_default },
    { "ftruncate", &fprint_syscall_default },
    { "getdents", &fprint_syscall_default },
    { "getcwd", &fprint_syscall_default },
    { "chdir", &fprint_syscall_default },
    { "fchdir", &fprint_syscall_default },
    { "rename", &fprint_syscall_default },
    { "mkdir", &fprint_syscall_default },
    { "rmdir", &fprint_syscall_default },
    { "creat", &fprint_syscall_default },
    { "link", &fprint_syscall_default },
    { "unlink", &fprint_syscall_default },
    { "symlink", &fprint_syscall_default },
    { "readlink", &fprint_syscall_default },
    { "chmod", &fprint_syscall_default },
    { "fchmod", &fprint_syscall_default },
    { "chown", &fprint_syscall_default },
    { "fchown", &fprint_syscall_default },
    { "lchown", &fprint_syscall_default },
    { "umask", &fprint_syscall_default },
    { "gettimeofday", &fprint_syscall_default },
    { "getrlimit", &fprint_syscall_default },
    { "getrusage", &fprint_syscall_default },
    { "sysinfo", &fprint_syscall_default },
    { "times", &fprint_syscall_default },
    { "ptrace", &fprint_syscall_default },
    { "getuid", &fprint_syscall_default },
    { "syslog", &fprint_syscall_default },
    { "getgid", &fprint_syscall_default },
    { "setuid", &fprint_syscall_default },
    { "setgid", &fprint_syscall_default },
    { "geteuid", &fprint_syscall_default },
    { "getegid", &fprint_syscall_default },
    { "setpgid", &fprint_syscall_default },
    { "getppid", &fprint_syscall_default },
    { "getpgrp", &fprint_syscall_default },
    { "setsid", &fprint_syscall_default },
    { "setreuid", &fprint_syscall_default },
    { "setregid", &fprint_syscall_default },
    { "getgroups", &fprint_syscall_default },
    { "setgroups", &fprint_syscall_default },
    { "setresuid", &fprint_syscall_default },
    { "getresuid", &fprint_syscall_default },
    { "setresgid", &fprint_syscall_default },
    { "getresgid", &fprint_syscall_default },
    { "getpgid", &fprint_syscall_default },
    { "setfsuid", &fprint_syscall_default },
    { "setfsgid", &fprint_syscall_default },
    { "getsid", &fprint_syscall_default },
    { "capget", &fprint_syscall_default },
    { "capset", &fprint_syscall_default },
    { "rt_sigpending", &fprint_syscall_default },
    { "rt_sigtimedwait", &fprint_syscall_default },
    { "rt_sigqueueinfo", &fprint_syscall_default },
    { "rt_sigsuspend", &fprint_syscall_default },
    { "sigaltstack", &fprint_syscall_default },
    { "utime", &fprint_syscall_default },
    { "mknod", &fprint_syscall_default },
    { "uselib", &fprint_syscall_default },
    { "personality", &fprint_syscall_default },
    { "ustat", &fprint_syscall_default },
    { "statfs", &fprint_syscall_default },
    { "fstatfs", &fprint_syscall_default },
    { "sysfs", &fprint_syscall_default },
    { "getpriority", &fprint_syscall_default },
    { "setpriority", &fprint_syscall_default },
    { "sched_setparam", &fprint_syscall_default },
    { "sched_getparam", &fprint_syscall_default },
    { "sched_setscheduler", &fprint_syscall_default },
    { "sched_getscheduler", &fprint_syscall_default },
    { "sched_get_priority_max", &fprint_syscall_default },
    { "sched_get_priority_min", &fprint_syscall_default },
    { "sched_rr_get_interval", &fprint_syscall_default },
    { "mlock", &fprint_syscall_default },
    { "munlock", &fprint_syscall_default },
    { "mlockall", &fprint_syscall_default },
    { "munlockall", &fprint_syscall_default },
    { "vhangup", &fprint_syscall_default },
    { "modify_ldt", &fprint_syscall_default },
    { "pivot_root", &fprint_syscall_default },
    { "_sysctl", &fprint_syscall_default },
    { "prctl", &fprint_syscall_default },
    { "arch_prctl", &fprint_syscall_default },
    { "adjtimex", &fprint_syscall_default },
    { "setrlimit", &fprint_syscall_default },
    { "chroot", &fprint_syscall_default },
    { "sync", &fprint_syscall_default },
    { "acct", &fprint_syscall_default },
    { "settimeofday", &fprint_syscall_default },
    { "mount", &fprint_syscall_default },
    { "umount2", &fprint_syscall_default },
    { "swapon", &fprint_syscall_default },
    { "swapoff", &fprint_syscall_default },
    { "reboot", &fprint_syscall_default },
    { "sethostname", &fprint_syscall_default },
    { "setdomainname", &fprint_syscall_default },
    { "iopl", &fprint_syscall_default },
    { "ioperm", &fprint_syscall_default },
    { "create_module", &fprint_syscall_default },
    { "init_module", &fprint_syscall_default },
    { "delete_module", &fprint_syscall_default },
    { "get_kernel_syms", &fprint_syscall_default },
    { "query_module", &fprint_syscall_default },
    { "quotactl", &fprint_syscall_default },
    { "nfsservctl", &fprint_syscall_default },
    { "getpmsg", &fprint_syscall_default },
    { "putpmsg", &fprint_syscall_default },
    { "afs_syscall", &fprint_syscall_default },
    { "tuxcall", &fprint_syscall_default },
    { "security", &fprint_syscall_default },
    { "gettid", &fprint_syscall_default },
    { "readahead", &fprint_syscall_default },
    { "setxattr", &fprint_syscall_default },
    { "lsetxattr", &fprint_syscall_default },
    { "fsetxattr", &fprint_syscall_default },
    { "getxattr", &fprint_syscall_default },
    { "lgetxattr", &fprint_syscall_default },
    { "fgetxattr", &fprint_syscall_default },
    { "listxattr", &fprint_syscall_default },
    { "llistxattr", &fprint_syscall_default },
    { "flistxattr", &fprint_syscall_default },
    { "removexattr", &fprint_syscall_default },
    { "lremovexattr", &fprint_syscall_default },
    { "fremovexattr", &fprint_syscall_default },
    { "tkill", &fprint_syscall_default },
    { "time", &fprint_syscall_default },
    { "futex", &fprint_syscall_default },
    { "sched_setaffinity", &fprint_syscall_default },
    { "sched_getaffinity", &fprint_syscall_default },
    { "set_thread_area", &fprint_syscall_default },
    { "io_setup", &fprint_syscall_default },
    { "io_destroy", &fprint_syscall_default },
    { "io_getevents", &fprint_syscall_default },
    { "io_submit", &fprint_syscall_default },
    { "io_cancel", &fprint_syscall_default },
    { "get_thread_area", &fprint_syscall_default },
    { "lookup_dcookie", &fprint_syscall_default },
    { "epoll_create", &fprint_syscall_default },
    { "epoll_ctl_old", &fprint_syscall_default },
    { "epoll_wait_old", &fprint_syscall_default },
    { "remap_file_pages", &fprint_syscall_default },
    { "getdents64", &fprint_syscall_default },
    { "set_tid_address", &fprint_syscall_default },
    { "restart_syscall", &fprint_syscall_default },
    { "semtimedop", &fprint_syscall_default },
    { "fadvise64", &fprint_syscall_default },
    { "timer_create", &fprint_syscall_default },
    { "timer_settime", &fprint_syscall_default },
    { "timer_gettime", &fprint_syscall_default },
    { "timer_getoverrun", &fprint_syscall_default },
    { "timer_delete", &fprint_syscall_default },
    { "clock_settime", &fprint_syscall_default },
    { "clock_gettime", &fprint_syscall_default },
    { "clock_getres", &fprint_syscall_default },
    { "clock_nanosleep", &fprint_syscall_default },
    { "exit_group", &fprint_syscall_default },
    { "epoll_wait", &fprint_syscall_default },
    { "epoll_ctl", &fprint_syscall_default },
    { "tgkill", &fprint_syscall_default },
    { "utimes", &fprint_syscall_default },
    { "vserver", &fprint_syscall_default },
    { "mbind", &fprint_syscall_default },
    { "set_mempolicy", &fprint_syscall_default },
    { "get_mempolicy", &fprint_syscall_default },
    { "mq_open", &fprint_syscall_default },
    { "mq_unlink", &fprint_syscall_default },
    { "mq_timedsend", &fprint_syscall_default },
    { "mq_timedreceive", &fprint_syscall_default },
    { "mq_notify", &fprint_syscall_default },
    { "mq_getsetattr", &fprint_syscall_default },
    { "kexec_load", &fprint_syscall_default },
    { "waitid", &fprint_syscall_default },
    { "add_key", &fprint_syscall_default },
    { "request_key", &fprint_syscall_default },
    { "keyctl", &fprint_syscall_default },
    { "ioprio_set", &fprint_syscall_default },
    { "ioprio_get", &fprint_syscall_default },
    { "inotify_init", &fprint_syscall_default },
    { "inotify_add_watch", &fprint_syscall_default },
    { "inotify_rm_watch", &fprint_syscall_default },
    { "migrate_pages", &fprint_syscall_default },
    { "openat", &fprint_syscall_default },
    { "mkdirat", &fprint_syscall_default },
    { "mknodat", &fprint_syscall_default },
    { "fchownat", &fprint_syscall_default },
    { "futimesat", &fprint_syscall_default },
    { "newfstatat", &fprint_syscall_default },
    { "unlinkat", &fprint_syscall_default },
    { "renameat", &fprint_syscall_default },
    { "linkat", &fprint_syscall_default },
    { "symlinkat", &fprint_syscall_default },
    { "readlinkat", &fprint_syscall_default },
    { "fchmodat", &fprint_syscall_default },
    { "faccessat", &fprint_syscall_default },
    { "pselect6", &fprint_syscall_default },
    { "ppoll", &fprint_syscall_default },
    { "unshare", &fprint_syscall_default },
    { "set_robust_list", &fprint_syscall_default },
    { "get_robust_list", &fprint_syscall_default },
    { "splice", &fprint_syscall_default },
    { "tee", &fprint_syscall_default },
    { "sync_file_range", &fprint_syscall_default },
    { "vmsplice", &fprint_syscall_default },
    { "move_pages", &fprint_syscall_default },
    { "utimensat", &fprint_syscall_default },
    { "epoll_pwait", &fprint_syscall_default },
    { "signalfd", &fprint_syscall_default },
    { "timerfd_create", &fprint_syscall_default },
    { "eventfd", &fprint_syscall_default },
    { "fallocate", &fprint_syscall_default },
    { "timerfd_settime", &fprint_syscall_default },
    { "timerfd_gettime", &fprint_syscall_default },
    { "accept4", &fprint_syscall_default },
    { "signalfd4", &fprint_syscall_default },
    { "eventfd2", &fprint_syscall_default },
    { "epoll_create1", &fprint_syscall_default },
    { "dup3", &fprint_syscall_default },
    { "pipe2", &fprint_syscall_default },
    { "inotify_init1", &fprint_syscall_default },
    { "preadv", &fprint_syscall_default },
    { "pwritev", &fprint_syscall_default },
    { "rt_tgsigqueueinfo", &fprint_syscall_default },
    { "perf_event_open", &fprint_syscall_default },
    { "recvmmsg", &fprint_syscall_default },
    { "fanotify_init", &fprint_syscall_default },
    { "fanotify_mark", &fprint_syscall_default },
    { "prlimit64", &fprint_syscall_default },
    { "name_to_handle_at", &fprint_syscall_default },
    { "open_by_handle_at", &fprint_syscall_default },
    { "clock_adjtime", &fprint_syscall_default },
    { "syncfs", &fprint_syscall_default },
    { "sendmmsg", &fprint_syscall_default },
    { "setns", &fprint_syscall_default },
    { "getcpu", &fprint_syscall_default },
    { "process_vm_readv", &fprint_syscall_default },
    { "process_vm_writev", &fprint_syscall_default },
    { "kcmp", &fprint_syscall_default },
    { "finit_module", &fprint_syscall_default },
    { "sched_setattr", &fprint_syscall_default },
    { "sched_getattr", &fprint_syscall_default },
    { "renameat2", &fprint_syscall_default },
    { "seccomp", &fprint_syscall_default },
    { "getrandom", &fprint_syscall_default },
    { "memfd_create", &fprint_syscall_default },
    { "kexec_file_load", &fprint_syscall_default },
    { "bpf", &fprint_syscall_default },
    { "execveat", &fprint_syscall_default },
    { "userfaultfd", &fprint_syscall_default },
    { "membarrier", &fprint_syscall_default },
    { "mlock2", &fprint_syscall_default },
    { "copy_file_range", &fprint_syscall_default },
    { "preadv2", &fprint_syscall_default },
    { "pwritev2", &fprint_syscall_default },
    { "pkey_mprotect", &fprint_syscall_default },
    { "pkey_alloc", &fprint_syscall_default },
    { "pkey_free", &fprint_syscall_default },
    { "statx", &fprint_syscall_default },
    { "io_pgetevents", &fprint_syscall_default },
    { "rseq", &fprint_syscall_default },
    { "uretprobe", &fprint_syscall_default },
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    { "pidfd_send_signal", &fprint_syscall_default },
    { "io_uring_setup", &fprint_syscall_default },
    { "io_uring_enter", &fprint_syscall_default },
    { "io_uring_register", &fprint_syscall_default },
    { "open_tree", &fprint_syscall_default },
    { "move_mount", &fprint_syscall_default },
    { "fsopen", &fprint_syscall_default },
    { "fsconfig", &fprint_syscall_default },
    { "fsmount", &fprint_syscall_default },
    { "fspick", &fprint_syscall_default },
    { "pidfd_open", &fprint_syscall_default },
    { "clone3", &fprint_syscall_default },
    { "close_range", &fprint_syscall_default },
    { "openat2", &fprint_syscall_default },
    { "pidfd_getfd", &fprint_syscall_default },
    { "faccessat2", &fprint_syscall_default },
    { "process_madvise", &fprint_syscall_default },
    { "epoll_pwait2", &fprint_syscall_default },
    { "mount_setattr", &fprint_syscall_default },
    { "quotactl_fd", &fprint_syscall_default },
    { "landlock_create_ruleset", &fprint_syscall_default },
    { "landlock_add_rule", &fprint_syscall_default },
    { "landlock_restrict_self", &fprint_syscall_default },
    { "memfd_secret", &fprint_syscall_default },
    { "process_mrelease", &fprint_syscall_default },
    { "futex_waitv", &fprint_syscall_default },
    { "set_mempolicy_home_node", &fprint_syscall_default },
    { "cachestat", &fprint_syscall_default },
    { "fchmodat2", &fprint_syscall_default },
    { "map_shadow_stack", &fprint_syscall_default },
    { "futex_wake", &fprint_syscall_default },
    { "futex_wait", &fprint_syscall_default },
    { "futex_requeue", &fprint_syscall_default },
    { "statmount", &fprint_syscall_default },
    { "listmount", &fprint_syscall_default },
    { "lsm_get_self_attr", &fprint_syscall_default },
    { "lsm_set_self_attr", &fprint_syscall_default },
    { "lsm_list_modules", &fprint_syscall_default },
    {0},
    { "setxattrat", &fprint_syscall_default },
    { "getxattrat", &fprint_syscall_default },
    { "listxattrat", &fprint_syscall_default },
    { "removexattrat", &fprint_syscall_default },
    { "open_tree_attr", &fprint_syscall_default },
};

#endif // __SYSCALL_META